default: &default
  adapter: sqlite3
  encoding: utf8
  pool: 5
  username: root
  password:
  timeout: 5000
# socket: /tmp/sqlite3.sock

development:
  <<: *default
  database: protospace-in-dev_development

test:
  <<: *default
  database: protospace-in-dev_test

production:
  <<: *default
  database: protospace-in-dev_production
  username: protospace-in-dev
  password: <%= ENV['PROTOSPACE-IN-DEV_DATABASE_PASSWORD'] %>
